### ISSUE TITLE
plugin execution fails with segmentation violation

### ISSUE THREAD

**Issue by OCram85** [woodpecker-ci/plugin-extend-env#3]
Just tested it with:
```yaml
steps:
  woodpecker-env:
    image: ubuntu:22.04
    pull: true
    commands:
      - env | sort
 
  extend-env:
    image: woodpeckerci/plugin-extend-env:next

  pwsh-image:
    image:  registry.ocram85.com/pwsh-cibase:latest
    commands:
      - env | sort
      - ls -la
      - cat .env
```

Got this runtime error:
![image](https://github.com/woodpecker-ci/plugin-extend-env/assets/13993700/234a5be9-2b12-41f9-96c1-e58a1e08997a)
